# Generated by Django 3.2.16 on 2023-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apple_store_link', models.URLField(blank=True, null=True, verbose_name='Apple Store Link')),
                ('google_play_store_link', models.URLField(blank=True, null=True, verbose_name='Google Play Store Link')),
            ],
            options={
                'verbose_name': 'App Stores Link',
                'verbose_name_plural': 'App Stores Link',
            },
        ),
    ]
