# Generated by Django 3.2.16 on 2023-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appstorelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstorelink',
            name='apple_store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='home/app_stores', verbose_name='Apple Store Logo'),
        ),
        migrations.AddField(
            model_name='appstorelink',
            name='google_play_store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='home/app_stores', verbose_name='Google Play Store Logo'),
        ),
    ]
