# Generated by Django 3.2.16 on 2022-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
