# Generated by Django 3.2.16 on 2022-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20221202_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(max_length=32, null=True, verbose_name='Apple Product ID'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('apple_product_id__isnull', False)), fields=('apple_product_id',), name='plan_apple_product_id_unique'),
        ),
    ]
