# Generated by Django 3.2.16 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_upgrade_charge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('apple_iap', 'apple_iap'), ('stripe_card', 'Stripe Card')], default=None, max_length=20, null=True, verbose_name='Payment Type'),
        ),
    ]
