# Generated by Django 3.2.15 on 2022-10-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSignalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(editable=False, max_length=250, null=True, verbose_name='App ID')),
                ('device_id', models.CharField(editable=False, max_length=250, verbose_name='Device ID')),
                ('device_type', models.PositiveIntegerField(choices=[(0, 'iOS'), (1, 'Android'), (2, 'Amazon'), (3, 'WindowsPhone (MPNS)'), (4, 'Chrome Apps / Extensions'), (5, 'Chrome Web Push'), (6, 'Windows (WNS)'), (7, 'Safari'), (8, 'Firefox'), (9, 'MacOS'), (10, 'Alexa'), (11, 'Email'), (13, 'Huawei App Gallery Builds. Not for Huawei Devices using FCM'), (14, 'SMS')])),
                ('identifier', models.CharField(blank=True, help_text='For Push Notifications, this is the Push Token Identifier from Google or Apple. For Apple Push identifiers, you must strip all non alphanumeric characters.', max_length=250, null=True, verbose_name='Identifier')),
                ('email_address', models.EmailField(blank=True, help_text='set the full email address email@email.com and make sure to set device_type to 11.', max_length=254, null=True, verbose_name='Email Addresses')),
                ('phone_number', models.CharField(blank=True, help_text='set the E.164 format and make sure to set device_type to 14.', max_length=20, null=True, verbose_name='Phone Number')),
                ('language', models.CharField(default='en', help_text='Language code. Typically lower case two letters, except for Chinese where it must be one of zh-Hans or zh-Hant. Example: en', max_length=10, verbose_name='Language')),
                ('device_model', models.CharField(help_text='Device make and model.', max_length=250, verbose_name='Device Model')),
                ('device_os', models.CharField(help_text='Device operating system version.', max_length=250, verbose_name='Device OS')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onesignal_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OneSignal Device',
                'verbose_name_plural': 'OneSignal Devices',
                'ordering': ('-created',),
            },
        ),
    ]
